### ISSUE TITLE
[Tests] Add phpunit tests

### ISSUE THREAD

**Issue by Simperfit** [Oblady/scoopit-topic-extractor#3]
You may have to add tests to the application using phpunit,

If you want to write there the test process, so @gorghoa or I could do it :+1:

**Comment by jtraulle** [comment]
Best way to test that, in my opinion is to create a Scoop.it account, scoop about two pages for a topic.
That way, we have a static topic that will never change (no new scoops added after that) and we can test expected extracted values for DOM parsing.
